base:
  template:
    - translations
    - tilt
    - extra_styles
  variables:
    state_on: >
      [[[ 
        if (entity?.attributes?.preset_mode == 'manual') {
            if (entity?.attributes?.temperature > 5) {
                return true;
            }
        }
        return ['on', 'home', 'cool', 'fan_only', 'playing', 'unlocked'].indexOf(!entity || entity.state) !== -1; 
      ]]]
    state: >
      [[[ 
        if (entity?.attributes?.preset_mode == 'manual') {
            if (entity?.attributes?.temperature > 5) {
                return 'on';
            }
        }
        return !entity || entity.state; 
      ]]]
    entity_id: >
      [[[ return !entity || entity.entity_id; ]]]
    entity_picture: >
      [[[ return !entity || entity.attributes.entity_picture; ]]]
    timeout: >
      [[[ return !entity || Date.now() - Date.parse(entity.last_changed); ]]]
    is_youtube: >
      [[[
        let is_youtube = entity?.attributes?.app_id === 'com.google.ios.youtube',
            sensor = this?._config?.triggers_update,
            media_title = entity?.attributes?.media_title,
            watching_title = states[sensor]?.attributes?.title;
        if (is_youtube && media_title === watching_title) {
            return true;
        }
      ]]]
  aspect_ratio: 1/1
  styles:
    grid:
      - grid-template-areas: |
          "icon  circle"
          "n     n"
          "s     s"
      - grid-template-columns: repeat(2, 1fr)
      - grid-template-rows: auto repeat(2, min-content)
      - gap: 1.3%
      - align-items: start
    name:
      - justify-self: start
      - line-height: 121%
    state:
      - justify-self: start
      - line-height: 115%
    card:
      - border-radius: var(--button-card-border-radius)
      - -webkit-tap-highlight-color: rgba(0,0,0,0)
      - transition: none
      - --mdc-ripple-color: >
          [[[
            return variables.state_on
                ? 'rgb(0, 0, 0)'
                : '#97989c';
          ]]]
      - color: >
          [[[
            return variables.state_on
                ? '#4b5254'
                : '#97989c';
          ]]]
      - background-color: >
          [[[
            return variables.state_on
                ? 'var(--button-card-background-color-active)'
                : 'var(--button-card-background-color-inactive)';
          ]]]
  tap_action:
    card_bounce: |
      [[[
        // add animation
        if (this.getElementsByTagName("style").length === 0) {
            // phone condition
            let mq = window.matchMedia('(max-width: 800px)').matches;
            let style = document.createElement('style');
            style.innerHTML = `
                @keyframes card_bounce {
                    0%   { transform: scale(1); }
                    10%  { transform: scale(${ mq ? '0.92' : '0.94' }); }
                    25%  { transform: scale(1); }
                    30%  { transform: scale(${ mq ? '0.96' : '0.98' }); }
                    100% { transform: scale(1); }
                }
            `;
            this.appendChild(style);
        }
        // duration
        let duration = 800;
        // animate
        this.style.animation = `card_bounce ${duration}ms cubic-bezier(0.22, 1, 0.36, 1)`;
        // reset
        window.setTimeout(() => { this.style.animation = "none"; }, duration + 100)
      ]]]
    action: toggle
  double_tap_action:
    action: more-info
  hold_action:
    action: none
  show_name: true
  show_icon: false
  show_state: true
  state_display: >
    [[[ 
        if (variables.state === true) {
            return variables.translate_unknown; 
        }
    ]]]

base_small:
  template:
    - base
  styles:
    grid:
      - grid-template-areas: |
          "icon"
          "n"
      - grid-template-columns: 1
      - grid-template-rows: 1
      - align-items: center
    name:
      - justify-self: center
      - line-height: 110%
      - font-size: 0.95em
    state:
      - justify-self: center
      - line-height: 80%
    custom_fields:
      icon:
        - width: 50%
        - margin-left: 0
        - justify-self: center
        - margin-left: 0 !important
  show_state: false

base_medium:
  template:
    - base_small
  styles:
    custom_fields:
      icon:
        - width: 70%