homeassistant:
  unit_system: metric
  temperature_unit: C
  time_zone: Europe/Berlin
  country: DE
  currency: EUR
  packages: !include_dir_named packages

sun:
wake_on_lan:
default_config:
tts:
  - platform: google_translate

frontend: !include themes.yaml

lovelace:
  mode: yaml
  resources:
    [
      { url: /hacsfiles/button-card/button-card.js,                                 type: module },
      { url: /hacsfiles/lovelace-layout-card/layout-card.js,                        type: module },
      { url: /hacsfiles/swipe-card/swipe-card.js,                                   type: module },
      { url: /hacsfiles/upcoming-media-card/upcoming-media-card.js,                 type: module },
      { url: /hacsfiles/lovelace-mushroom/mushroom.js,                              type: module },
      { url: /hacsfiles/bar-card/bar-card.js,                                       type: module },
      { url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js,                  type: module },
      { url: /hacsfiles/scheduler-card/scheduler-card.js,                           type: module },
      { url: /hacsfiles/weather-card/weather-card.js,                               type: module },
      { url: /hacsfiles/LG-WebOS-Remote-Control/lg-remote-control.js,               type: module },
      { url: /hacsfiles/lovelace-auto-entities/auto-entities.js,                    type: module },
      { url: /hacsfiles/harmony-card/harmony-card.js,                               type: module },
      { url: /hacsfiles/kiosk-mode/kiosk-mode.js,                                   type: module },
      { url: /hacsfiles/custom-icons/custom-icons.js,                               type: module },
      { url: /hacsfiles/apexcharts-card/apexcharts-card.js,                         type: module },

      { url: '/local/marked.min.js?v=4.2.1',                                        type: module },
      { url: '/local/vanilla-tilt.min.js?v=1.7.3',                                  type: module },
      { url: '/local/browser_mod_icon.js?v=0.5',                                    type: module },
      { url: '/local/fonts.css?v=2.1',                                              type: css }
    ]

logger:
  default: info
  logs:
    custom_components.hacs: debug