button_card_templates: !include_dir_merge_named button_card_templates

kiosk_mode:
  user_settings:
    - users:
        - "kiosk"
      hide_header: true

views:
  - type: custom:grid-layout
    path: 0
    layout:
      #default
      margin: 0
      grid-gap: var(--custom-layout-card-padding)
      grid-template-columns: 0 repeat(4, 1fr) 0
      grid-template-rows: 0 repeat(2, fit-content(100%)) 0fr
      grid-template-areas: |
        ". . . . . ."
        ". wohnzimmer  media bad rest ."
        ". schlafzimmer kueche flur home ."
        ". footer footer . . ."
      mediaquery:
        #phone
        "(max-width: 800px)":
          grid-gap: calc(var(--custom-layout-card-padding) * 1.7)
          grid-template-columns: 0 repeat(1, 1fr) 0
          grid-template-rows: 0 repeat(5, fit-content(100%)) 0fr
          grid-template-areas: |
            ". . ."
            ". wohnzimmer ."
            ". media ."
            ". bad ."
            ". rest ."
            ". schlafzimmer ."
            ". kueche ."
            ". flur ."
            ". home ."
            ". footer ."
            ". . ."
        #portrait
        "(max-width: 1200px)":
          grid-gap: var(--custom-layout-card-padding)
          grid-template-columns: 0 repeat(2, 1fr) 0
          grid-template-rows: 0 repeat(3, fit-content(100%)) 0fr
          grid-template-areas: |
            ". . . ."
            ". wohnzimmer media ."
            ". bad rest ."
            ". schlafzimmer kueche ."
            ". flur home ."
            ". footer footer ."
        #portrait2
        "(max-width: 1600px)":
          grid-gap: var(--custom-layout-card-padding)
          grid-template-columns: 0 repeat(3, 1fr) 0
          grid-template-rows: 0 repeat(3, fit-content(100%)) 0fr
          grid-template-areas: |
            ". . . . ."
            ". wohnzimmer media bad ."
            ". rest schlafzimmer kueche ."
            ". flur home . ."
            ". footer footer . ."
    cards:
      #extra_styles fix, do not remove
      #also warn if theme is not set

      - type: custom:button-card
        view_layout:
          grid-area: 1 / 2 / 2 / 5
        name: SET THEME TO "tablet" IN PROFILE
        tap_action:
          action: navigate
          navigation_path: /profile
        styles:
          card:
            - display: >
                [[[
                  return hass.themes.theme === 'tablet'
                      ? 'none'
                      : 'initial';
                ]]]
          name:
            - z-index: 1
            - overflow: visible
            - color: red
            - font-weight: bolder
            - font-size: xxx-large
            - background: yellow

      #################################################
      #                                               #
      #                    WOHNZIMMER                 #
      #                                               #
      #################################################
      - type: grid
        title: Wohnzimmer
        view_layout:
          grid-area: wohnzimmer
        columns: 2
        cards:
          - type: custom:swipe-card
            parameters:
              autoplay:
                pauseOnMouseEnter: true
                delay: 13000
              effect: flip
              speed: 550
              spaceBetween: 40
              threshold: 5
            cards:
              - type: custom:button-card
                entity: climate.wohnzimmer
                template:
                  - climate
                  - icon_heater

              - type: custom:button-card
                entity: sensor.multisensor_wohnzimmer_temperature
                template:
                  - graph_temperature

              - type: custom:button-card
                entity: sensor.multisensor_wohnzimmer_humidity
                template:
                  - graph_humidity

              - type: custom:button-card
                entity: sensor.multisensor_wohnzimmer_pressure
                template:
                  - graph_pressure

          - type: custom:button-card
            entity: light.schreibtisch
            name: Schreibtisch
            template:
              - light
              - icon_hue

          - type: custom:button-card
            entity: light.stehlampe
            name: Stehlampe
            template:
              - light
              - icon_shade

          - type: custom:button-card
            entity: light.wohnzimmer
            name: Decke
            template:
              - light
              - icon_spot

      #################################################
      #                                               #
      #                    MEDIA                      #
      #                                               #
      #################################################
      - type: grid
        title: Media
        view_layout:
          grid-area: media
        columns: 1
        cards:
          - type: custom:swipe-card
            parameters:
              autoplay:
                pauseOnMouseEnter: true
                delay: 6000
              speed: 550
              spaceBetween: 40
              threshold: 5
            cards:
              #              - type: custom:button-card
              #                entity: sensor.trakt_upcoming_shows
              #                name: TV
              #                template:
              #                  - trakt

              - type: grid
                columns: 2
                cards:
                  - type: custom:button-card
                    entity: media_player.desktop_s43pn6o
                    name: PC
                    template:
                      - media
                      - icon_imac
                      - icon_play_pause

                  - type: custom:button-card
                    entity: media_player.osmc
                    name: Kodi
                    template:
                      - media
                      - icon_tv
                      - icon_play_pause

                  - type: custom:button-card
                    entity: media_player.spotify_daniel
                    name: Spotify
                    template:
                      - media
                      - icon_spotify
                      - icon_play_pause

                  - type: custom:button-card
                    entity: media_player.nestmini
                    name: Nest Mini
                    template:
                      - media
                      - icon_nest_mini
                      - icon_play_pause

              - type: custom:button-card
                entity: remote.harmony_hub
                template:
                  - harmony

      #################################################
      #                                               #
      #                    BAD                        #
      #                                               #
      #################################################
      - type: grid
        title: Bad
        view_layout:
          grid-area: bad
        columns: 2
        cards:
          - type: custom:swipe-card
            parameters:
              autoplay:
                pauseOnMouseEnter: true
                delay: 13000
              effect: flip
              speed: 550
              spaceBetween: 40
              threshold: 5
            cards:
              - type: custom:button-card
                entity: climate.bad
                template:
                  - climate
                  - icon_heater

              - type: custom:button-card
                entity: sensor.multisensor_bad_temperature
                template:
                  - graph_temperature

              - type: custom:button-card
                entity: sensor.multisensor_bad_humidity
                template:
                  - graph_humidity

              - type: custom:button-card
                entity: sensor.multisensor_bad_pressure
                template:
                  - graph_pressure

          - type: custom:button-card
            entity: binary_sensor.kontaktsensor_bad
            name: Fenster
            tap_action:
              action: more-info
            template:
              - base
              - icon_bathroom

      #################################################
      #                                               #
      #                    Rest                       #
      #                                               #
      #################################################
      - type: grid
        title: Rest
        view_layout:
          grid-area: rest
        columns: 2
        cards:
          - type: custom:button-card
            entity: light.essbereich
            name: Essbereich
            template:
              - light
              - icon_hue

          - type: custom:button-card
            entity: light.ecke
            name: Ecke
            template:
              - light
              - icon_ledstripe

          - type: custom:button-card
            entity: light.couch
            name: Couch
            template:
              - light
              - icon_hue

          - type: grid
            columns: 2
            cards:
              - type: custom:button-card
                entity: switch.lufterfrischer
                name: Febreze 1
                template:
                  - icon_fan2
                  - base_small
                  - loader

              - type: custom:button-card
                entity: switch.lufterfrischer_2
                name: Febreze 2
                template:
                  - icon_fan2
                  - base_small
                  - loader

              - type: custom:button-card
                entity: switch.insektenvernichter
                name: Insektenvernichter
                template:
                  - icon_fan2
                  - base_small
                  - loader

              - type: custom:button-card
                entity: switch.wallpanel_battery
                name: Wallpanel
                template:
                  - icon_fan2
                  - base_small
                  - loader

      #################################################
      #                                               #
      #                     Schlafzimmer              #
      #                                               #
      #################################################
      - type: grid
        title: Schlafzimmer
        view_layout:
          grid-area: schlafzimmer
        columns: 2
        cards:
          - type: custom:swipe-card
            parameters:
              autoplay:
                pauseOnMouseEnter: true
                delay: 13000
              effect: flip
              speed: 550
              spaceBetween: 40
              threshold: 5
            cards:
              - type: custom:button-card
                entity: climate.schlafzimmer
                template:
                  - climate
                  - icon_heater

              - type: custom:button-card
                entity: sensor.multisensor_schlafzimmer_temperature
                template:
                  - graph_temperature

              - type: custom:button-card
                entity: sensor.multisensor_schlafzimmer_humidity
                template:
                  - graph_humidity

              - type: custom:button-card
                entity: sensor.multisensor_schlafzimmer_pressure
                template:
                  - graph_pressure

          - type: custom:button-card
            entity: light.schlafzimmer
            name: Schlafzimmer
            template:
              - light
              - icon_ceiling_light

      #################################################
      #                                               #
      #                     Flur                      #
      #                                               #
      #################################################
      - type: grid
        title: Flur
        view_layout:
          grid-area: flur
        columns: 2
        cards:
          - type: custom:swipe-card
            parameters:
              autoplay:
                pauseOnMouseEnter: true
                delay: 13000
              effect: flip
              speed: 550
              spaceBetween: 40
              threshold: 5
            cards:
              - type: custom:button-card
                entity: sensor.bewegungsmelder_flur_temperature
                template:
                  - graph_temperature

              - type: custom:button-card
                entity: sensor.bewegungsmelder_flur_illuminance
                template:
                  - graph_illuminance

          - type: custom:button-card
            entity: light.flur
            name: Flur
            template:
              - light
              - nested_presence_sensor_flur
              - icon_spot

      #################################################
      #                                               #
      #                     Küche                     #
      #                                               #
      #################################################
      - type: grid
        title: Küche
        view_layout:
          grid-area: kueche
        columns: 2
        cards:
          - type: custom:button-card
            entity: light.kitchen
            name: Küche
            template:
              - light
              - icon_ledstripe

          - type: custom:button-card
            entity: binary_sensor.kontaktsensor_kuche
            name: Fenster
            tap_action:
              action: more-info
            template:
              - base
              - icon_closet

      #################################################
      #                                               #
      #                     HOME                      #
      #                                               #
      #################################################

      - type: grid
        title: Home
        view_layout:
          grid-area: home
        columns: 2
        cards:
          - type: custom:button-card
            entity: person.daniel
            name: Daniel
            double_tap_action: !include popup/popup_daniel.yaml
            template:
              - person
              - icon_home

          - type: custom:button-card
            entity: none
            template:
              - energy

      #################################################
      #                                               #
      #                    FOOTER                     #
      #                                               #
      #################################################

      - type: horizontal-stack
        view_layout:
          grid-area: footer
        cards:
          - type: custom:button-card
            name: >
              <ha-icon icon="mdi:clock-outline"></ha-icon> Scheduler
            tap_action: !include popup/footer_scheduler.yaml
            variables:
              notify: >
                [[[
                  return false;
                ]]]
            template: footer

          - type: custom:button-card
            name: >
              <ha-icon icon="mdi:weather-sunny"></ha-icon> Wetter
            tap_action: !include popup/footer_weather.yaml
            variables:
              notify: >
                [[[
                  return false;
                ]]]
            template: footer

          - type: custom:button-card
            name: >
              <ha-icon icon="mdi:tablet"></ha-icon> Tablet
            tap_action: !include popup/footer_tablet.yaml
            variables:
              notify: >
                [[[
                  let is_charging = states['binary_sensor.nexus_9_is_charging'];
                  let battery = states['sensor.nexus_9_battery_level'];
                  return is_charging.state == 'off' && parseInt(battery.state) <= 30;
                ]]]
            template: footer

          - type: custom:button-card
            name: >
              <ha-icon icon="mdi:battery"></ha-icon> Batterien
            tap_action: !include popup/footer_battery.yaml
            variables:
              notify: >
                [[[
                  return false;
                ]]]
            template: footer
