input_datetime:
  heating_start:
    name: Heating Automation Start Time
    has_date: false
    has_time: true
    initial: "06:00:00"
  heating_stop:
    name: Heating Automation Stop Time
    has_date: false
    has_time: true
    initial: "17:00:00"

input_number:
  heating_trigger_temp:
    name: Heating Automation Trigger Temperature
    initial: 21.0
    min: 20.0
    max: 22.0
    step: 1
  heating_target_temp:
    name: Heating Automation Target Temperature
    initial: 23.0
    min: 22.0
    max: 24.0
    step: 1

input_boolean:
