device_tracker:
  - platform: bluetooth_tracker
    new_device_defaults:
      track_new_devices: true

  - platform: tado
    username: !secret tado_username
    password: !secret tado_password
    home_id: !secret tado_home_id